--questions
select * from customers

--1)what is the total revenue generated by male vs female customers?
select gender,sum(purchase_amount) as revenue
from customers
group by gender;

--2)which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customers
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customers)

--3)which are the top 5 products with the highest average review rating?
select item_purchased,avg(review_rating) as "Average rating"
from customers
group by item_purchased
order by avg(review_rating) desc
limit 5

--4)compare the average purchase amounts between standard and express shipping?
select shipping_type, ROUND(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type;

--5)Do subscribed customers spend more?compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id) as total_customers,
ROUND(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customers
group by subscription_status
order by avg_spend, total_revenue desc;

--6)which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*sum(case when discount_applied='Yes' then 1 else 0 END)/count(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5

--7)segment customers into new, returning,and loyal based on their total number of previous purchases,
    --and show the count of each segment
with customers_type as(
select customer_id,previous_purchase
case 
	when previous_purchase = 1 then "New"
	when previous_purchase between 2 and 10 then "Returning"
	else "Loyal"
	end as customer_segment
from customers)
select custo

--8)what are the top 3 most purchased products within each category?
with item_counts as(
select category,item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased)

select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3

--9)Are customers who are repeat buyers (more than 5 previous purchase)also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customers
where previous_purchases>5
group by subscription_status

--10)what is the revenue contribution of each age group
select age_group,sum(purchase_amount)as total_revenue
from customers
group by age_group
order by total_revenue desc
